### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by erneyramirez** [phonchi/Cryo-RAlib#8]
I have read your article about the method and I find it very interesting. I would like to use it.
I have tried to install it but I am having some problems.

SPHIRE installation: .................................................check
    SPARX v5.0 (GITHUB: 2021-03-08 11:36)

MPI available: .......................................................check
Traceback (most recent call last):
  File "lib_check.py", line 100, in <module>
    sys.exit( main(sys.argv) )
  File "lib_check.py", line 67, in main
    ver = [ entry for entry in ver.split("\n") if entry != "" ]
TypeError: a bytes-like object is required, not 'str'

**Comment by phonchi** [comment]
Dear erneyramirez:
The code is tested under the environment of EMAN2.31 (which uses Python2). The problem seems like arise from the different behavior between Python2 and Python3. You could try to change the environment to EMAN2.31.

**Comment by erneyramirez** [comment]
Thank you very much! 
With your help I was able to install Cryo-RAlib.
However, I am getting errors when running it. I copy it below in case you can help me.
------------------------------------------------------------
(/data2/erney/scipion3_conda/software/em/eman-2.91) [erney@torvalds2 Cryo-RAlib]$ mpirun -np 4 ./test_mref_cheng_yu_bdb_cuda.py /home/erney/data_hilbert_tres/test_cryoRAlib/rib80s_ori_bin.hdf /home/erney/data_hilbert_tres/test_cryoRAlib/rib80s_ref.hdf /home/erney/data_hilbert_tres/test_cryoRAlib --ou=36 --xr=3 --yr=3 --gpu_devices=6
[torvalds2:86107] *** Process received signal ***
[torvalds2:86107] Signal: Segmentation fault (11)
[torvalds2:86107] Signal code: Address not mapped (1)
[torvalds2:86107] Failing at address: 0x10
[torvalds2:86109] *** Process received signal ***
[torvalds2:86109] Signal: Segmentation fault (11)
[torvalds2:86109] Signal code: Address not mapped (1)
[torvalds2:86109] Failing at address: 0x10
[torvalds2:86108] *** Process received signal ***
[torvalds2:86108] Signal: Segmentation fault (11)
[torvalds2:86108] Signal code: Address not mapped (1)
[torvalds2:86108] Failing at address: 0x10
[torvalds2:86109] [ 0] /lib64/libpthread.so.0(+0xf5f0)[0x7f8bb54285f0]
[torvalds2:86109] [ 1] /home/erney/data/scipion3_conda/software/em/eman-2.91/lib/python3.7/site-packages/mpi.so(+0x94a9)[0x7f8b957174a9]
[torvalds2:86109] [ 2] [torvalds2:86107] [ 0] /lib64/libpthread.so.0(+0xf5f0)[0x7fadde5925f0]
[torvalds2:86107] [ 1] /home/erney/data/scipion3_conda/software/em/eman-2.91/lib/python3.7/site-packages/mpi.so(+0x94a9)[0x7fadbf0954a9]
[torvalds2:86107] [ 2] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(_PyMethodDef_RawFastCallKeywords+0x1e0)[0x56457ad0fa30]
[torvalds2:86109] [ 3] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(_PyMethodDef_RawFastCallKeywords+0x1e0)[0x55bc1ac43a30]
[torvalds2:86107] [ 3] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(_PyCFunction_FastCallKeywords+0x21)[0x55bc1ac43bd1]
[torvalds2:86107] [ 4] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(_PyEval_EvalFrameDefault+0x47a4)[0x55bc1aca9e54]
[torvalds2:86107] [ 5] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(_PyEval_EvalCodeWithName+0x2f9)[0x55bc1abef389]
[torvalds2:86107] [ 6] [torvalds2:86108] [ 0] /lib64/libpthread.so.0(+0xf5f0)[0x7f827c3bf5f0]
[torvalds2:86108] [ 1] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(_PyCFunction_FastCallKeywords+0x21)[0x56457ad0fbd1]
[torvalds2:86109] [ 4] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(_PyEval_EvalFrameDefault+0x47a4)[0x56457ad75e54]
[torvalds2:86109] [ 5] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(_PyEval_EvalCodeWithName+0x2f9)[0x56457acbb389]
[torvalds2:86109] [ 6] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(_PyFunction_FastCallKeywords+0x387)[0x56457ad0f2b7]
[torvalds2:86109] [ 7] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(_PyFunction_FastCallKeywords+0x387)[0x55bc1ac432b7]
[torvalds2:86107] [ 7] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(_PyEval_EvalFrameDefault+0x14d4)[0x55bc1aca6b84]
[torvalds2:86107] [ 8] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(_PyFunction_FastCallKeywords+0xfb)[0x55bc1ac4302b]
[torvalds2:86107] [ 9] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(_PyEval_EvalFrameDefault+0x416)[0x55bc1aca5ac6]
[torvalds2:86107] [10] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(_PyEval_EvalCodeWithName+0x2f9)[0x55bc1abef389]
[torvalds2:86107] [11] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(PyEval_EvalCodeEx+0x44)[0x55bc1abf02b4]
[torvalds2:86107] [12] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(PyEval_EvalCode+0x1c)[0x55bc1abf02dc]
[torvalds2:86107] [13] /home/erney/data/scipion3_conda/software/em/eman-2.91/lib/python3.7/site-packages/mpi.so(+0x94a9)[0x7f82686bd4a9]
[torvalds2:86108] [ 2] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(_PyMethodDef_RawFastCallKeywords+0x1e0)[0x55a95dfc8a30]
[torvalds2:86108] [ 3] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(_PyCFunction_FastCallKeywords+0x21)[0x55a95dfc8bd1]
[torvalds2:86108] [ 4] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(_PyEval_EvalFrameDefault+0x47a4)[0x55a95e02ee54]
[torvalds2:86108] [ 5] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(_PyEval_EvalFrameDefault+0x14d4)[0x56457ad72b84]
[torvalds2:86109] [ 8] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(_PyFunction_FastCallKeywords+0xfb)[0x56457ad0f02b]
[torvalds2:86109] [ 9] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(_PyEval_EvalFrameDefault+0x416)[0x56457ad71ac6]
[torvalds2:86109] [10] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(_PyEval_EvalCodeWithName+0x2f9)[0x56457acbb389]
[torvalds2:86109] [11] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(PyEval_EvalCodeEx+0x44)[0x56457acbc2b4]
[torvalds2:86109] [12] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(PyEval_EvalCode+0x1c)[0x56457acbc2dc]
[torvalds2:86109] [13] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(+0x22c664)[0x55bc1ad06664]
[torvalds2:86107] [14] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(+0x22c664)[0x56457add2664]
[torvalds2:86109] [14] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(PyRun_FileExFlags+0xa1)[0x56457addca91]
[torvalds2:86109] [15] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(PyRun_SimpleFileExFlags+0x1c3)[0x56457addcc83]
[torvalds2:86109] [16] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(+0x237db5)[0x56457addddb5]
[torvalds2:86109] [17] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(_Py_UnixMain+0x3c)[0x56457adddedc]
[torvalds2:86109] [18] /lib64/libc.so.6(__libc_start_main+0xf5)[0x7f8bb506d505]
[torvalds2:86109] [19] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(+0x1db3e0)[0x56457ad813e0]
[torvalds2:86109] *** End of error message ***
/home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(_PyEval_EvalCodeWithName+0x2f9)[0x55a95df74389]
[torvalds2:86108] [ 6] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(_PyFunction_FastCallKeywords+0x387)[0x55a95dfc82b7]
[torvalds2:86108] [ 7] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(_PyEval_EvalFrameDefault+0x14d4)[0x55a95e02bb84]
[torvalds2:86108] [ 8] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(_PyFunction_FastCallKeywords+0xfb)[0x55a95dfc802b]
[torvalds2:86108] [ 9] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(_PyEval_EvalFrameDefault+0x416)[0x55a95e02aac6]
[torvalds2:86108] [10] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(_PyEval_EvalCodeWithName+0x2f9)[0x55a95df74389]
[torvalds2:86108] [11] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(PyEval_EvalCodeEx+0x44)[0x55a95df752b4]
[torvalds2:86108] [12] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(PyRun_FileExFlags+0xa1)[0x55bc1ad10a91]
[torvalds2:86107] [15] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(PyRun_SimpleFileExFlags+0x1c3)[0x55bc1ad10c83]
[torvalds2:86107] [16] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(+0x237db5)[0x55bc1ad11db5]
[torvalds2:86107] [17] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(_Py_UnixMain+0x3c)[0x55bc1ad11edc]
[torvalds2:86107] [18] /lib64/libc.so.6(__libc_start_main+0xf5)[0x7fadde1d7505]
[torvalds2:86107] [19] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(+0x1db3e0)[0x55bc1acb53e0]
[torvalds2:86107] *** End of error message ***
/home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(PyEval_EvalCode+0x1c)[0x55a95df752dc]
[torvalds2:86108] [13] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(+0x22c664)[0x55a95e08b664]
[torvalds2:86108] [14] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(PyRun_FileExFlags+0xa1)[0x55a95e095a91]
[torvalds2:86108] [15] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(PyRun_SimpleFileExFlags+0x1c3)[0x55a95e095c83]
[torvalds2:86108] [16] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(+0x237db5)[0x55a95e096db5]
[torvalds2:86108] [17] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(_Py_UnixMain+0x3c)[0x55a95e096edc]
[torvalds2:86108] [18] /lib64/libc.so.6(__libc_start_main+0xf5)[0x7f827c004505]
[torvalds2:86108] [19] /home/erney/data/scipion3_conda/software/em/eman-2.91/bin/python(+0x1db3e0)[0x55a95e03a3e0]
[torvalds2:86108] *** End of error message ***
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
  File "./test_mref_cheng_yu_bdb_cuda.py", line 1617, in <module>
    main()
  File "./test_mref_cheng_yu_bdb_cuda.py", line 1313, in main
    Blockdata["total_nima"] = global_def.EMUtil.get_image_count(args[0])
  File "/home/erney/data/scipion3_conda/software/em/eman-2.91/lib/python3.7/site-packages/EMAN2db.py", line 657, in db_get_image_count
    ret = EMUtil.get_image_count_c(fsp)
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 0 on node torvalds2 exited on signal 11 (Segmentation fault).

**Comment by erneyramirez** [comment]
I get the above error if I run the code with eman2.9, using eman2.3 I have been able to run the program correctly.

Thank you!
